function sd  = wt_dirs

sr            = wt_root;

% During the overhauling of the 2018 year the following directories have
% been removed because they implements the old functionality
%
%        fullfile(sr,'WTData',filesep,'SteConLaws'), ...


sd  = { ...
        fullfile(sr,'bem'), ...
        fullfile(sr,'bemOptimization'), ...
        fullfile(sr,'common'), ...
        fullfile(sr,'dimensioning'), ...
        fullfile(sr,'dynamicStall'), ...
        fullfile(sr,'fatigue'), ...
        fullfile(sr,'fatigue',filesep,'rainflow'), ...
        fullfile(sr,'Noise'), ...
        fullfile(sr,'options'), ...
        fullfile(sr,'stallDelay'), ...
        fullfile(sr,'loads'), ...
        fullfile(sr,'structural'), ...
        fullfile(sr,'tdcma'), ...
        fullfile(sr,'Testing'), ...
        fullfile(sr,'Testing',filesep,'bem'), ...
        fullfile(sr,'Testing',filesep,'clVortexShedding'), ...        
        fullfile(sr,'Testing',filesep,'dimensioning'), ...
        fullfile(sr,'Testing',filesep,'dynamicStall'), ...
        fullfile(sr,'Testing',filesep,'eigen'), ...
        fullfile(sr,'Testing',filesep,'initial'), ...
        fullfile(sr,'Testing',filesep,'loads'), ...
        fullfile(sr,'Testing',filesep,'massCost'), ...
        fullfile(sr,'Testing',filesep,'optimization'), ...
        fullfile(sr,'Testing',filesep,'sclaw'), ...
        fullfile(sr,'Testing',filesep,'structural'), ...
        fullfile(sr,'Testing',filesep,'tdcma'), ...
        fullfile(sr,'Testing',filesep,'validation'), ...
        fullfile(sr,'Testing',filesep,'wesdof'), ...
        fullfile(sr,'Testing',filesep,'wind'), ...
        fullfile(sr,'Testing',filesep,'windMann'), ...
        fullfile(sr,'VibrationAnalysis'), ...
        fullfile(sr,'wesdof'), ...
        fullfile(sr,'wsssp2ts'), ...
        fullfile(sr,'wsssp2ts',filesep,'wind'), ...
        fullfile(sr,'wsssp2ts',filesep,'wind',filesep,'mann'), ...
        fullfile(sr,'wsssp2ts',filesep,'clVortexShedding'), ...        
        fullfile(sr,'WTData'), ...
        fullfile(sr,'WTData',filesep,'Airfoils'), ...
        fullfile(sr,'WTData',filesep,'avatar'), ...
        fullfile(sr,'WTData',filesep,'blade'), ...
        fullfile(sr,'WTData',filesep,'dtu10MW'), ...
        fullfile(sr,'WTData',filesep,'ebb'), ...
        fullfile(sr,'WTData',filesep,'iea10MW'), ...
        fullfile(sr,'WTData',filesep,'iea15MW'), ...
        fullfile(sr,'WTData',filesep,'iea15MWMod'), ...
        fullfile(sr,'WTData',filesep,'iea3400kW'), ...
        fullfile(sr,'WTData',filesep,'lmh64_5'), ...
        fullfile(sr,'WTData',filesep,'Material'), ...
        fullfile(sr,'WTData',filesep,'motherblade'), ...
        fullfile(sr,'WTData',filesep,'ndBlade'), ...
        fullfile(sr,'WTData',filesep,'nrel5MW'), ...
        fullfile(sr,'WTData',filesep,'nrelUAE'), ...
        fullfile(sr,'WTData',filesep,'nrelUAEdata'), ...
        fullfile(sr,'WTData',filesep,'sclaw'), ...        
        fullfile(sr,'WTData',filesep,'site'), ...
        fullfile(sr,'WTData',filesep,'snl100'), ...        
        fullfile(sr,'WTData',filesep,'VoShAero'), ...
        fullfile(sr,'wtdb'), ...
        fullfile(sr,'wtDoc'), ...
        fullfile(sr,'wtDoc',filesep,'html'), ...
        fullfile(sr,'wtDoc',filesep,'wtDemos'), ...
        fullfile(sr,'wtDoc',filesep,'icon'), ...
        fullfile(sr,'yaw') ...
};

